included:
  - GitManager
  - GitManagerTests
excluded:
  - Pods
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - closure_body_length
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_unwrapping
  - force_try
  - force_cast
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - xct_specific_matcher
  - xctfail_message
  - yoda_condition

nesting:
  type_level:
    warning: 4
  statement_level:
    warning: 12

identifier_name:
  min_length: 3
  max_length: 40
  validate_start_with_lowercase: true
  excluded:
    - id
    - x
    - y
    - z
    - dx
    - dy

closure_body_length:
  warning: 80
  error: 120

file_length:
  warning: 700
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 120
  error: 150

line_length:
  warning: 140
  error: 160
  ignores_urls: true
  ignores_comments: false

type_body_length:
  warning: 600
  error: 800