# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'GitManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitManager
  pod 'SwiftLint'
  pod 'SnapshotTesting', '~> 1.9.0'
  pod 'RemoteImage', :path => '../RemoteImage'

  target 'GitManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
  
